### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mountainash** [mountainash/taskana#19]
There are many outdated dependencies ([raised as pull requests](https://github.com/mountainash/taskana/pulls)) that need to be upgraded and then the app tested to see it still works, before marking the merge for approval.

**Comment by PPInfy** [comment]
Assign this issue to me

**Comment by PPInfy** [comment]
Hi @mountainash - I have forked this. Please take my fork and check if any issues are there. I dont have an asana account so cant test it myself.

**Comment by mountainash** [comment]
Last time I looked Asana was free to signup for. You'll need an account (and to be signed in) to test if...

- [ ]  the menu items work, 
- [ ] key commands function, and 
- [ ] the app icon badge shows when when you get a notification (new inbox item)

Testing these details is the primary purpose for this task.
