### ISSUE TITLE
Command + N not working

### ISSUE THREAD

**Issue by mountainash** [mountainash/taskana#64]
The keyboard short cut has stopped working (Asana's probably changed the DOM, will need to remap to a selector)

**Comment by Shylajhaa** [comment]
@mountainash Is this issue available to pickup? Also are there any steps to reproduce?

**Comment by mountainash** [comment]
It sure is!

Very easy, open the app (latest version), press cmd + n on your keyboard.... and anticlimax, nothing happens. 

If you look in the menu code you'll see that there's an event that's likely triggering but the dom element that it's calling a "click" on, no longer exists. 

Open the normal Asana website in a browser and use the dev tools Inspector to try and find the new DOM path to the button/link that creates a new task (spawns the modal to create a new task). All the best, reach out if you need any help.

**Comment by Shylajhaa** [comment]
> It sure is!
> 
> Very easy, open the app (latest version), press cmd + n on your keyboard.... and anticlimax, nothing happens.
> 
> If you look in the menu code you'll see that there's an event that's likely triggering but the dom element that it's calling a "click" on, no longer exists.
> 
> Open the normal Asana website in a browser and use the dev tools Inspector to try and find the new DOM path to the button/link that creates a new task (spawns the modal to create a new task). All the best, reach out if you need any help.

Can you assign it to me?

**Comment by mountainash** [comment]
@Shylajhaa how's it going? Need any help?

**Comment by Shylajhaa** [comment]
When I run `npm start`, multiple windows keep opening

**Comment by mountainash** [comment]
Yes, I noticed that on the weekend and merged a fix. Rebase from the develop branch to fix it.

**Comment by mountainash** [comment]
Nice work! Thank you. I'll merge it now.

Would you like to take a look at #65 also and I can merge them both into the next release?

**Comment by mountainash** [comment]
@Shylajhaa - this has broken again, would you like to update it again? #71

**Comment by Shylajhaa** [comment]
> @Shylajhaa - this has broken again, would you like to update it again? #71

Sure @mountainash Will look into it

**Comment by Shylajhaa** [comment]
@mountainash Guess this is done?

**Comment by Shylajhaa** [comment]
@mountainash Is there any way this could be automated or any other better way to handle this instead of devs having to update the dom changes everytime? 
If yes, I would be interested in taking it up.

**Comment by mountainash** [comment]
Sure; using Electron as basically just a Webview is a quick way to get an "Asana app" with all the hard work already done by Asana. They also provide an API that, given time, you could write your own app on top of... but that's an entirely new project - maybe you want to start that?

**Comment by Shylajhaa** [comment]
> Sure; using Electron as basically just a Webview is a quick way to get an "Asana app" with all the hard work already done by Asana. They also provide an API that, given time, you could write your own app on top of... but that's an entirely new project - maybe you want to start that?

Sounds like a good idea @mountainash. But would like to know the impact, in case we build a revamped taskana (built over asana APIs).
Approx how many users currently use taskana?

**Comment by mountainash** [comment]
The app has no tracking (and I'm not looking to add any). Based on the number of Issues raised by the "community" (less than 10) and a few forks... and that no-one complains when it stops working for weeks on end; I'd be surprised if their was more than a few people using it.

If you looking for "impact" in terms of users... don't bother - you'd need to do it for your own personal itch.

**Comment by Shylajhaa** [comment]
> The app has no tracking (and I'm not looking to add any). Based on the number of Issues raised by the "community" (less than 10) and a few forks... and that no-one complains when it stops working for weeks on end; I'd be surprised if their was more than a few people using it.
> 
> If you looking for "impact" in terms of users... don't bother - you'd need to do it for your own personal itch.

Understood @mountainash. Would be happy to collaborate with you on any other future projects. It was great working on `taskana` 🎉😄

**Comment by mountainash** [comment]
Thank you so much for the kind words. If you're interested; there's a similar project I occasionally work on, which is also similar to Taskana (an Electron wrapper of an online service) called [Mixcloud-Play](https://github.com/mountainash/Mixcloud-Play) which has much more scope for improvement, fixes and has more users (from what I can tell). There's already a nice list of [open issues](https://github.com/mountainash/Mixcloud-Play/issues) you can jump straight into.

**Comment by Shylajhaa** [comment]
Sure, I will take a look at them and comment on the issues
